name: Tierrajusta
favicon: null
layout_spectrum: 0.5883728237822652
typography_spectrum: 0.3602730880957097
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.195213659433648
  lightness: 0.09400209621526301
  saturation: 0.6093612948898226
  rhythmicContrast: 0.8567588487640023
purpose: []
